### ISSUE TITLE
Search url has changed

### ISSUE THREAD

**Issue by covolution** [Alfresco/health-care-app#10]
The live search url has changed from

public/alfresco/versions/1/queries/live-search-nodes
 to
public/alfresco/versions/1/queries/nodes

You may also like to try out the new full search api:

public/search/versions/1/search

**Comment by magemello** [comment]
Hi,

thanks for the comment, we are already tracking this issue on the main components repository, you can follow the progress from there:

https://github.com/Alfresco/alfresco-ng2-components/issues/555

Thank you

**Comment by wabson** [comment]
Upstream issue has been closed and this app has now been upgraded to use the latest component, closing.
