### ISSUE TITLE
Error when uploading image during Create Patient

### ISSUE THREAD

**Issue by wabson** [Alfresco/health-care-app#19]
When uploading an image from the Create Patient component, the `fileUploaded()` handler is called twice, once with the response object from the successful upload and a second time with the object `{value: "file aborted"}` and this results in an error being thrown by the subsequent code.

<img width="1015" alt="screen shot 2017-02-10 at 15 03 36" src="https://cloud.githubusercontent.com/assets/1727487/22831446/4bd2f4a4-efa2-11e6-9337-df7758a50ecf.png">

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
