### ISSUE TITLE
UI does not fallback to english if native browser locale is not available => many labels missing

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/health-care-app#28]
App is affected as well by : 

https://github.com/Alfresco/alfresco-ng2-components/issues/1608

Many labels are missing therefore, if you have any language other than english in your browser. 

![health_language](https://cloud.githubusercontent.com/assets/1854212/22970918/2caa0bbe-f374-11e6-87de-419d7c8cf2f5.png)

**Comment by wabson** [comment]
Fix for Alfresco/alfresco-ng2-components#1608 should address this at the component level, however changes will also be needed in the app

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
