### ISSUE TITLE
Name column in Visits tasklist is always empty

### ISSUE THREAD

**Issue by wabson** [Alfresco/health-care-app#29]
A value should be displayed for this, instead it is empty and only the Visit Type column is populated

<img width="348" alt="screen shot 2017-02-15 at 12 57 26" src="https://cloud.githubusercontent.com/assets/1727487/22975557/1cb155ea-f37f-11e6-822e-02524c3d638f.png">

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
