### ISSUE TITLE
Settings drawer displayed after logging out

### ISSUE THREAD

**Issue by wabson** [Alfresco/health-care-app#30]
When clicking Logout the settings drawer is displayed on the LHS of the page. It should only be displayed when the icon is clicked to expand it.

<img width="1425" alt="screen shot 2017-02-15 at 12 56 49" src="https://cloud.githubusercontent.com/assets/1727487/22975526/fcf2f074-f37e-11e6-89f8-07d9436ef1f5.png">

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
