### ISSUE TITLE
Impossible to update ECM and BPM urls

### ISSUE THREAD

**Issue by tokamak** [Alfresco/health-care-app#31]
When changing the urls from ECM or BPM the following exception occurs and the change is not taken into account : 
"self.context.onChangeBPMHost is not a function at ..."
![updateecmbpmurls2](https://cloud.githubusercontent.com/assets/5611353/23066654/fba29e42-f51b-11e6-8642-7b4fd2b1d865.png)

Though, I manage to update the URL manually by updating the variables in app.component.ts

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
