### ISSUE TITLE
changing ECM or BPM port leads to exception.

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/health-care-app#32]
Steps to reproduce : 

1. Click on the "triple bar" on the top left 
2. change the port to either the ECM or BPM 
3. type enter. Chrome console leads to this exception : 

> TypeError: self.context.onChangeECMHost is not a function
>     at CompiledTemplate.proxyViewClass.View_AppComponent0.handleEvent_74 (/AppModule/AppComponent/component.ngfactory.js:643)
>     at CompiledTemplate.proxyViewClass.eval (eval at <anonymous> (vendor.js:101), <anonymous>:9474:41)
>     at HTMLInputElement.eval (eval at <anonymous> (vendor.js:209), <anonymous>:1468:40)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.js:3239), <anonymous>:265:35)
>     at Object.onInvokeTask (eval at <anonymous> (vendor.js:101), <anonymous>:5966:41)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.js:3239), <anonymous>:264:40)
>     at Zone.runTask (eval at <anonymous> (polyfills.js:3239), <anonymous>:154:47)
>     at HTMLInputElement.ZoneTask.invoke (eval at <anonymous> (polyfills.js:3239), <anonymous>:335:33)

Same goes for BPM. 
I initially thought this only happened when accesssing the app from another host than where the whole stack is running but i've managed to reproduce this while accessing it as well from the same host.

Also not sure why the port settings shown in this pane are different from each host ? how is this stored ? 

Using ADF 1.1. 
npm  3.10.10  node  v6.9.5, provided by Fedora 25.

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
