### ISSUE TITLE
Activiti 401 doesn't show an error.

### ISSUE THREAD

**Issue by covolution** [Alfresco/health-care-app#9]
If I have EMC running and not BPM then i get an error trying to login, that's all good.  However, if I have them both running but Activiti returns a 401 then no error message is displayed.  The form just does nothing - no error, no feedback to the user.

**Comment by magemello** [comment]
Hi, I raised a new issue on the components repository:

https://github.com/Alfresco/alfresco-ng2-components/issues/795

Thank you

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
